version: '3.4'

services:
  germes:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  db:
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=client-barometer
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
        - './db:/var/lib/mysql'
    ports:
      - "3307:3306"

  front:
    volumes:
      - ./src/Front:/app
    ports:
      - 3000:3000

  ngrok:
    environment:
      - NGROK_AUTH=${NGROK_TOKEN}
      - NGROK_LOOK_DOMAIN=${BACK_URL}
      - NGROK_PORT=${BACK_PORT}
      - NGROK_DEBUG=true
    ports:
      - "6020:4040"
