name: Deploy Pipeline

on:
  push:
    branches: [master]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
          sudo chmod 600 ~/.ssh/private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SERVER_KNOWN_HOSTS}}

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/private.key $SERVER_USERNAME@$SERVER_IP_ADDRESS 'cd /apps/germes; sudo git pull --recurse-submodules; sudo docker-compose up --force-recreate --build -d germes;'
        env:
          SERVER_USERNAME: ${{secrets.SERVER_USERNAME}}
          SERVER_IP_ADDRESS: ${{secrets.SERVER_IP_ADDRESS}}
